server:
  port: 8080
spring:
  application:
    name: activiti-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/activity?characterEncoding=utf8&useSSL=true
    username: root
    password: qazwsx123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        #自动创建、更新、验证数据库表结构
        ddl-auto: update
  activiti:
    check-process-definitions: false